name: test everything
on: [push]

jobs:
  build-and-test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [8, 10, 12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'octocat'
        id: hello
      - name: Echo greeting
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: install
        run: yarn run install
      - name: build
        run: yarn run build
      - name: test
        run: yarn run test
