name: test
on: [push]

jobs:
  build-and-test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [8, 10, 12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-restore-cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install if no-cache
        # if: steps.yarn-restore-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: build
        run: yarn run build
      - name: test
        run: yarn run testci
      - uses: actions/upload-artifact@v1
        with:
          name: kits-test
          path: "*-test.json"
